name: Github Action Workflow DEV

on:
  push:
    branches:
      - staging
  repository_dispatch:
    types:
      - CICD-stage
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  CICD-stage:
    uses: Proyecto-DevOps-ORT/PRY-BackEnd-Payments/.github/workflows/ci-cd.yaml@staging
    with:
      CI_ENV: staging
      CONTENTFUL_ENVIRONMENT: 'staging'
      ORGANIZATION: 'Proyecto-DevOps-ORT'
      REPOSITORY: 'PRY-BackEnd-Payments'
      ECR_REPOSITORY: 'pry-backend-payments'
      POSTMAN_REPOSITORY_NAME: 'payments-service'
      IMAGE_TAG: 'staging'
      CLUSTER_NAME: 'ecs-cluster-backend'
      SERVICE_NAME: 'service-payments-stage'
      TASK_DEFINITION_NAME: 'task-def-payments-stage'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}