name: Github Action Workflow DEV



on:
  push:
    branches:
      - develop
  repository_dispatch:
    types:
      - CICD-dev
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  CICD-dev:
    uses: Proyecto-DevOps-ORT/PRY-BackEnd-Products/.github/workflows/ci-cd.yaml@develop #./.github/workflows/ci-cd.yml@develop
    with:
      CI_ENV: develop
      CONTENTFUL_ENVIRONMENT: 'develop'
      ORGANIZATION: 'Proyecto-DevOps-ORT'
      REPOSITORY: 'PRY-BackEnd-Products'
      ECR_REPOSITORY: 'pry-backend-products'
      POSTMAN_REPOSITORY_NAME: 'products-service'
      IMAGE_TAG: 'develop'
      CLUSTER_NAME: 'ecs-cluster-backend'
      SERVICE_NAME: 'service-products-dev'
      TASK_DEFINITION_NAME: 'task-def-products-dev'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}